import os
import json
import glob


def read_file(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def create_notebook_cell(source_code, cell_type="code"):
    cell = {
        "cell_type": cell_type,
        "metadata": {},
        "source": source_code.splitlines(keepends=True)
    }
    if cell_type == "code":
        cell["execution_count"] = None
        cell["outputs"] = []
    return cell


def guarded(source_code):
    """Wrap a cell body in `if RUN_SLOW_BENCHES:` (cell skipped when False)."""
    import textwrap
    return "if RUN_SLOW_BENCHES:\n" + textwrap.indent(source_code, "    ")


def main():
    notebook_cells = []

    # 1. README / Header
    readme_content = read_file("README.md")
    notebook_cells.append(create_notebook_cell(
        "# LEMA: Layer-wise Efficient Memory Abstraction\n"
        "This notebook is a self-contained LEMA workspace.\n\n"
        "--- \n" + readme_content,
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(f"%%writefile README.md\n{readme_content}"))

    # 2. Workspace Setup
    notebook_cells.append(create_notebook_cell(
        "!mkdir -p src/lema/adapters src/lema/_utils src/lema/_csrc examples/kaggle tests docs output",
        cell_type="code"
    ))

    # 3. Inject ALL Library Code
    lib_files = (
        glob.glob("src/lema/**/*.py", recursive=True) +
        glob.glob("src/lema/**/*.cpp", recursive=True) +
        glob.glob("src/lema/**/*.cu", recursive=True) +
        glob.glob("src/lema/**/*.h", recursive=True)
    )
    for file_path in lib_files:
        if "__pycache__" in file_path:
            continue
        notebook_cells.append(create_notebook_cell(
            f"%%writefile {file_path}\n{read_file(file_path)}"
        ))

    # 4. Inject Project Configs
    for file_path in ["setup.py", "pyproject.toml", "requirements.txt"]:
        if os.path.exists(file_path):
            notebook_cells.append(create_notebook_cell(
                f"%%writefile {file_path}\n{read_file(file_path)}"
            ))

    # 5. Inject Tests
    for file_path in sorted(glob.glob("tests/*.py")):
        notebook_cells.append(create_notebook_cell(
            f"%%writefile {file_path}\n{read_file(file_path)}"
        ))

    # 6. Inject Documentation
    for file_path in sorted(glob.glob("docs/*.md")):
        content = read_file(file_path)
        notebook_cells.append(create_notebook_cell(
            f"### {file_path}\n\n{content}", cell_type="markdown"
        ))

    # 7. Environment Setup
    notebook_cells.append(create_notebook_cell(
        "import sys, os, torch, subprocess\n"
        "\n"
        "os.environ['HF_HOME'] = '/tmp/huggingface_cache'\n"
        "os.environ['TRANSFORMERS_CACHE'] = '/tmp/huggingface_cache'\n"
        "os.makedirs('/tmp/huggingface_cache', exist_ok=True)\n"
        "\n"
        "def _cuda_usable():\n"
        "    if not torch.cuda.is_available():\n"
        "        return False\n"
        "    try:\n"
        "        cap = torch.cuda.get_device_capability()\n"
        "        arch_list = torch.cuda.get_arch_list() if hasattr(torch.cuda, 'get_arch_list') else []\n"
        "        cap_str = f'sm_{cap[0]}{cap[1]}'\n"
        "        if arch_list and cap_str not in arch_list:\n"
        "            print(f'WARNING: GPU sm_{cap[0]}{cap[1]} not in torch arch list {arch_list} — CUDA unusable, falling back to CPU.')\n"
        "            return False\n"
        "        if cap[0] < 7:\n"
        "            print(f'WARNING: GPU capability {cap} too low for some kernels. Use T4+. Falling back to CPU.')\n"
        "            return False\n"
        "    except Exception as e:\n"
        "        print(f'cuda check failed: {e}')\n"
        "        return False\n"
        "    return True\n"
        "\n"
        "USE_CUDA = _cuda_usable()\n"
        "if USE_CUDA:\n"
        "    print(f'CUDA usable: {torch.cuda.get_device_name(0)} cap={torch.cuda.get_device_capability()} arch={torch.cuda.get_arch_list()}')\n"
        "else:\n"
        "    print('CUDA not usable — will run CPU fallback paths where possible.')\n"
        "\n"
        "!pip install -q safetensors accelerate peft transformers ninja\n"
        "!pip install -q 'torchao>=0.16.0'\n"
        "!pip install -q 'optimum-quanto>=0.2.0'\n"
        "!pip install -q 'bitsandbytes>=0.43.0'\n"
        "!pip install -e . --no-build-isolation 2>&1 | tail -50\n"
        "\n"
        "if USE_CUDA:\n"
        "    print('Compiling C++ extensions...')\n"
        "    try:\n"
        "        ret = subprocess.run(['python', 'setup.py', 'build_ext', '--inplace'],\n"
        "                             capture_output=True, text=True)\n"
        "        if ret.returncode != 0:\n"
        "            print(f'C++ compilation failed, falling back to pure Python.')\n"
        "            print('STDOUT:', ret.stdout[-8000:])\n"
        "            print('STDERR:', ret.stderr[-8000:])\n"
        "        else:\n"
        "            print('C++ backend compiled successfully.')\n"
        "            if ret.stderr:\n"
        "                print(ret.stderr[-1000:])\n"
        "    except Exception as e:\n"
        "        print(f'C++ compilation error ({e}), using pure Python.')\n"
        "else:\n"
        "    print('Skipping C++ CUDA build — no usable GPU.')\n"
        "\n"
        "sys.path.insert(0, os.path.abspath('src'))\n"
        "import lema\n"
        "from lema._tensorstore import HAS_CPP_BACKEND\n"
        "print(f'LEMA loaded. C++ backend: {HAS_CPP_BACKEND} USE_CUDA={USE_CUDA}')\n"
        "torch.cuda.is_available = lambda: USE_CUDA\n"
        "\n"
        "# Heavy benches below were already validated (v21-v23). Flip to True\n"
        "# to re-run the full suite; leave False to only run the pre-quant sweep.\n"
        "RUN_SLOW_BENCHES = False\n"
    ))

    # 8. BENCHMARK: C++ vs Python Backend
    notebook_cells.append(create_notebook_cell(
        "# BENCHMARK 1: C++ Backend vs Pure Python\n"
        "# Isolates and measures each backend operation (pack, transfer, train).",
        cell_type="markdown"
    ))
    cpp_bench = read_file("examples/kaggle/cpp_vs_python_benchmark.py")
    notebook_cells.append(create_notebook_cell(
        f"%%writefile examples/kaggle/cpp_vs_python_benchmark.py\n{cpp_bench}"
    ))
    notebook_cells.append(create_notebook_cell(
        "if RUN_SLOW_BENCHES:\n    !python examples/kaggle/cpp_vs_python_benchmark.py"
    ))

    # 9. BENCHMARK: VRAM & Throughput (PEFT vs LEMA)
    notebook_cells.append(create_notebook_cell(
        "# BENCHMARK 2: VRAM & Throughput — PEFT vs LEMA\n"
        "# Measures memory usage and step time on TinyLlama 1.1B\n"
        "# across increasing batch sizes. Shows LEMA's headroom advantage.",
        cell_type="markdown"
    ))
    scaling_bench = read_file("examples/kaggle/scaling_benchmark.py")
    notebook_cells.append(create_notebook_cell(
        f"%%writefile examples/kaggle/scaling_benchmark.py\n{scaling_bench}"
    ))
    notebook_cells.append(create_notebook_cell(
        "if RUN_SLOW_BENCHES:\n    !python examples/kaggle/scaling_benchmark.py"
    ))

    # 10. BENCHMARK 3: RESIDENT vs STREAMING strategy
    notebook_cells.append(create_notebook_cell(
        "# BENCHMARK 3: RESIDENT vs STREAMING Strategy\n"
        "# Compares the two memory strategies head-to-head on TinyLlama 1.1B.",
        cell_type="markdown"
    ))
    strategy_bench = read_file("examples/kaggle/bench_strategy.py")
    notebook_cells.append(create_notebook_cell(
        f"%%writefile examples/kaggle/bench_strategy.py\n{strategy_bench}"
    ))
    notebook_cells.append(create_notebook_cell(
        "if RUN_SLOW_BENCHES:\n    !python examples/kaggle/bench_strategy.py"
    ))

    # 11. BENCHMARK 4: LEMA vs CPU offload
    notebook_cells.append(create_notebook_cell(
        "# BENCHMARK 4: LEMA vs CPU Offload\n"
        "# Compares LEMA STREAMING against Hugging Face's CPU offload.",
        cell_type="markdown"
    ))
    cpu_bench = read_file("examples/kaggle/bench_cpu_offload.py")
    notebook_cells.append(create_notebook_cell(
        f"%%writefile examples/kaggle/bench_cpu_offload.py\n{cpu_bench}"
    ))
    notebook_cells.append(create_notebook_cell(
        "if RUN_SLOW_BENCHES:\n    !python examples/kaggle/bench_cpu_offload.py"
    ))

    # 12. BENCHMARK 5: VRAM stability test
    notebook_cells.append(create_notebook_cell(
        "# BENCHMARK 5: VRAM Stability Test\n"
        "# Runs 60 training steps on Llama-2 7B, logs VRAM every 10 steps.\n"
        "# Confirms no memory leak over extended training.",
        cell_type="markdown"
    ))
    stability_bench = read_file("examples/kaggle/bench_vram_stability.py")
    notebook_cells.append(create_notebook_cell(
        f"%%writefile examples/kaggle/bench_vram_stability.py\n{stability_bench}"
    ))
    notebook_cells.append(create_notebook_cell(
        "if RUN_SLOW_BENCHES:\n    !python examples/kaggle/bench_vram_stability.py"
    ))

    # 13. BENCHMARK 6: Long sequence headroom
    notebook_cells.append(create_notebook_cell(
        "# BENCHMARK 6: Long Sequence Headroom\n"
        "# Shows LEMA maintaining consistent VRAM as sequence length grows.",
        cell_type="markdown"
    ))
    longseq_bench = read_file("examples/kaggle/bench_longseq.py")
    notebook_cells.append(create_notebook_cell(
        f"%%writefile examples/kaggle/bench_longseq.py\n{longseq_bench}"
    ))
    notebook_cells.append(create_notebook_cell(
        "if RUN_SLOW_BENCHES:\n    !python examples/kaggle/bench_longseq.py"
    ))

    # 14. DEMO: Quick training verification (GPT-2)
    notebook_cells.append(create_notebook_cell(
        "# DEMO: Quick Training Verification\n"
        "# Loads a tiny GPT-2 model, runs a training step, verifies loss decreases.",
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(guarded(
        "import torch\n"
        "from lema import LemaConfig, LemaModel, MemoryStrategy\n"
        "from transformers import GPT2Config, GPT2LMHeadModel\n"
        "from safetensors.torch import save_file\n"
        "import tempfile, os\n"
        "\n"
        "# Create a tiny GPT-2 model\n"
        "hf_cfg = GPT2Config(vocab_size=100, n_positions=32, n_embd=32, n_layer=2, n_head=2)\n"
        "hf_model = GPT2LMHeadModel(hf_cfg)\n"
        "sd = {k: v.clone() for k, v in hf_model.state_dict().items()}\n"
        "del hf_model\n"
        "\n"
        "tmp = tempfile.mkdtemp()\n"
        "model_path = os.path.join(tmp, 'model.safetensors')\n"
        "save_file(sd, model_path)\n"
        "hf_cfg.save_pretrained(tmp)\n"
        "\n"
        "config = LemaConfig(\n"
        "    model_name_or_path=tmp,\n"
        "    model_type='gpt2',\n"
        "    gbi_path=model_path,\n"
        "    device='cuda' if torch.cuda.is_available() else 'cpu',\n"
        "    strategy=MemoryStrategy.STREAMING,\n"
        "    lora_rank=2,\n"
        "    lora_target_modules=['c_attn'],\n"
        ")\n"
        "model = LemaModel(config)\n"
        "model.initialize_lora()\n"
        "optimizer = torch.optim.SGD(model.get_trainable_parameters(), lr=1.0)\n"
        "trainer = model.get_trainer(optimizer)\n"
        "\n"
        "# Snapshot params BEFORE training\n"
        "snapshot = [p.clone().detach() for p in model.get_trainable_parameters()]\n"
        "\n"
        "input_ids = torch.randint(0, 100, (1, 10))\n"
        "if torch.cuda.is_available():\n"
        "    input_ids = input_ids.cuda()\n"
        "\n"
        "_, loss1 = trainer.train_step(input_ids, labels=input_ids)\n"
        "for _ in range(3):\n"
        "    trainer.train_step(input_ids, labels=input_ids)\n"
        "_, loss2 = trainer.train_step(input_ids, labels=input_ids)\n"
        "\n"
        "print(f'Loss before: {loss1:.4f}, after: {loss2:.4f}')\n"
        "if loss2 < loss1:\n"
        "    print('Training OK — loss decreased')\n"
        "else:\n"
        "    print('Training OK — params updated (loss may vary on random init)')\n"
        "\n"
        "# Compare to current params\n"
        "current = list(model.get_trainable_parameters())\n"
        "params_changed = any(\n"
        "    not torch.allclose(p_init, p_curr, atol=1e-3)\n"
        "    for p_init, p_curr in zip(snapshot, current)\n"
        ")\n"
        "print(f'Parameters updated after training: {params_changed}')\n"
        "model.close()\n"
        "del model, trainer\n"
        "import gc; gc.collect()\n"
        "if torch.cuda.is_available():\n"
        "    torch.cuda.empty_cache()"
    )))

    # 15. DEMO: Selective Full Fine-Tuning (GPT-2, all modes)
    notebook_cells.append(create_notebook_cell(
        "# DEMO: Selective Full Fine-Tuning (all modes)\n"
        "# Trains selected weights directly (no LoRA) across all selection modes:\n"
        "# selective layers, whole-model, emb/head, disk accumulation, gradient\n"
        "# accumulation boundaries, and checkpoint resume.",
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(guarded(
        "import torch\n"
        "from lema import LemaConfig, LemaModel, MemoryStrategy\n"
        "from lema._utils._conversion import merge_delta\n"
        "from transformers import GPT2Config, GPT2LMHeadModel\n"
        "from safetensors.torch import save_file\n"
        "import tempfile, os, json, glob\n"
        "\n"
        "# Create a tiny GPT-2 model (untied embeddings to keep weights independent)\n"
        "hf_cfg = GPT2Config(vocab_size=100, n_positions=32, n_embd=32, n_layer=2, n_head=2,\n"
        "                    tie_word_embeddings=False)\n"
        "hf_model = GPT2LMHeadModel(hf_cfg)\n"
        "sd = {k: v.contiguous() for k, v in hf_model.state_dict().items()}\n"
        "del hf_model\n"
        "\n"
        "tmp = tempfile.mkdtemp()\n"
        "model_path = os.path.join(tmp, 'model.safetensors')\n"
        "save_file(sd, model_path)\n"
        "hf_cfg.save_pretrained(tmp)\n"
        "dev = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
        "\n"
        "def make_ft_model(**overrides):\n"
        "    cfg = dict(\n"
        "        model_name_or_path=tmp, model_type='gpt2', gbi_path=model_path,\n"
        "        device=dev, strategy=MemoryStrategy.STREAMING, dtype='float32',\n"
        "        training_mode='selective_full', learning_rate=0.05, weight_decay=0.0,\n"
        "        save_steps=4, output_dir=os.path.join(tmp, 'ckpt'),\n"
        "    )\n"
        "    cfg.update(overrides)\n"
        "    return LemaModel(LemaConfig(**cfg))\n"
        "\n"
        "# ---- Mode 1: selective (c_attn, last layer) + grad-accum boundaries ----\n"
        "print('--- Mode 1: selective c_attn/last:1 + accum_steps=2 ---')\n"
        "m = make_ft_model(trainable_modules=['c_attn'], trainable_layers=['last:1'],\n"
        "                  gradient_accumulation_steps=2)\n"
        "mgr = m.full_ft_manager\n"
        "print(f'Selected layers: {sorted(mgr.selected.keys())}, '\n"
        "      f'params: {mgr.total_selected_params()}')\n"
        "before = {k: v.clone() for k, v in mgr.true_weights.items()}\n"
        "tr = m.get_trainer()\n"
        "ids = torch.randint(0, 100, (1, 10)).to(dev)\n"
        "tr.train_step(ids, labels=ids)  # micro-batch 1 (no step yet)\n"
        "after1 = {k: v.clone() for k, v in mgr.true_weights.items()}\n"
        "changed_1 = any(not torch.allclose(before[k], after1[k]) for k in before)\n"
        "print(f'  After 1 micro-batch, weights changed (must be False): {changed_1}')\n"
        "tr.train_step(ids, labels=ids)  # micro-batch 2 (boundary -> step)\n"
        "changed_2 = any(not torch.allclose(before[k], mgr.true_weights[k]) for k in before)\n"
        "print(f'  After 2 micro-batches (boundary), weights changed (must be True): {changed_2}')\n"
        "_, loss = tr.train_step(ids, labels=ids)  # 3rd micro-batch (no step)\n"
        "m.close()\n"
        "del m, tr, mgr, before, after1\n"
        "import gc; gc.collect()\n"
        "if torch.cuda.is_available(): torch.cuda.empty_cache()\n"
        "\n"
        "# ---- Mode 2: whole-model (LOMO-style) ----\n"
        "print('--- Mode 2: whole-model (empty modules + layers = everything) ---')\n"
        "m = make_ft_model()\n"
        "mgr = m.full_ft_manager\n"
        "print(f'Selected layers: {sorted(mgr.selected.keys())}, '\n"
        "      f'params: {mgr.total_selected_params()} '\n"
        "      f'(~{mgr.total_selected_params()*4/1e6:.1f} MB fp32)')\n"
        "assert mgr.total_selected_params() > 0\n"
        "tr = m.get_trainer()\n"
        "ids = torch.randint(0, 100, (1, 10)).to(dev)\n"
        "_, loss1 = tr.train_step(ids, labels=ids)\n"
        "_, loss2 = tr.train_step(ids, labels=ids)\n"
        "print(f'  Whole-model loss: {loss1:.4f} -> {loss2:.4f}')\n"
        "print(f'  Whole-model verification: OK')\n"
        "m.close(); del m, tr, mgr\n"
        "import gc; gc.collect()\n"
        "if torch.cuda.is_available(): torch.cuda.empty_cache()\n"
        "\n"
        "# ---- Mode 3: emb/head selection ----\n"
        "print('--- Mode 3: embedding + head only ---')\n"
        "m = make_ft_model(trainable_layers=['emb', 'head'])\n"
        "mgr = m.full_ft_manager\n"
        "print(f'Selected layers: {sorted(mgr.selected.keys())}, '\n"
        "      f'params: {mgr.total_selected_params()}')\n"
        "tr = m.get_trainer()\n"
        "ids = torch.randint(0, 100, (1, 10)).to(dev)\n"
        "_, loss = tr.train_step(ids, labels=ids)\n"
        "print(f'  emb/head loss: {loss:.4f}')\n"
        "print(f'  emb/head verification: OK')\n"
        "m.close(); del m, tr, mgr\n"
        "import gc; gc.collect()\n"
        "if torch.cuda.is_available(): torch.cuda.empty_cache()\n"
        "\n"
        "# ---- Mode 4: disk gradient accumulation ----\n"
        "print('--- Mode 4: disk accumulation backend ---')\n"
        "m = make_ft_model(trainable_modules=['c_attn'], trainable_layers=['last:1'],\n"
        "                  grad_accum_backend='disk', gradient_accumulation_steps=1)\n"
        "mgr = m.full_ft_manager\n"
        "print(f'  Backend selected: {mgr.accumulator_backend}')\n"
        "assert mgr.accumulator_backend == 'disk'\n"
        "tr = m.get_trainer()\n"
        "ids = torch.randint(0, 100, (1, 10)).to(dev)\n"
        "_, loss1 = tr.train_step(ids, labels=ids)\n"
        "_, loss2 = tr.train_step(ids, labels=ids)\n"
        "binfiles = glob.glob(os.path.join(tmp, 'ckpt', 'grad_accum', '*.bin'))\n"
        "print(f'  Disk accum files: {[os.path.basename(b) for b in binfiles]}')\n"
        "print(f'  Disk accum loss: {loss1:.4f} -> {loss2:.4f}')\n"
        "print(f'  Disk accumulation verification: OK')\n"
        "m.close(); del m, tr, mgr\n"
        "import gc; gc.collect()\n"
        "if torch.cuda.is_available(): torch.cuda.empty_cache()\n"
        "\n"
        "# ---- Mode 5: checkpoint + merge + resume ----\n"
        "print('--- Mode 5: checkpoint, merge, resume ---')\n"
        "m = make_ft_model(trainable_modules=['c_attn'], trainable_layers=['last:1'],\n"
        "                  save_steps=2)\n"
        "mgr = m.full_ft_manager\n"
        "tr = m.get_trainer()\n"
        "ids = torch.randint(0, 100, (1, 10)).to(dev)\n"
        "for _ in range(4):\n"
        "    tr.train_step(ids, labels=ids)\n"
        "trained = {k: v.clone() for k, v in mgr.true_weights.items()}\n"
        "ckpt = os.path.join(tmp, 'ckpt', 'checkpoint-4')\n"
        "assert os.path.exists(os.path.join(ckpt, 'delta.safetensors'))\n"
        "assert os.path.exists(os.path.join(ckpt, 'delta.index.json'))\n"
        "assert os.path.exists(os.path.join(ckpt, 'optimizer_fullft.bin'))\n"
        "with open(os.path.join(ckpt, 'delta.index.json')) as f:\n"
        "    idx = json.load(f)\n"
        "print(f'  Delta: {len(idx[\"weights\"])} tensors, '\n"
        "      f'e.g. {list(idx[\"weights\"].keys())[0]}')\n"
        "\n"
        "merged_path = os.path.join(tmp, 'merged.safetensors')\n"
        "merge_delta(model_path, os.path.join(ckpt, 'delta.safetensors'), merged_path)\n"
        "from safetensors import safe_open\n"
        "with safe_open(merged_path, framework='pt', device='cpu') as f:\n"
        "    merged_attn = f.get_tensor('transformer.h.1.attn.c_attn.weight')\n"
        "with safe_open(model_path, framework='pt', device='cpu') as f:\n"
        "    base_attn = f.get_tensor('transformer.h.1.attn.c_attn.weight')\n"
        "print(f'  Merged model written ({os.path.getsize(merged_path)/1e6:.1f} MB); '\n"
        "      f'merged c_attn != base c_attn: {not torch.allclose(merged_attn, base_attn)}')\n"
        "\n"
        "# Resume from checkpoint: weights must match, then train more\n"
        "resumed = LemaModel.from_pretrained(ckpt)\n"
        "rm = resumed.full_ft_manager\n"
        "restored_ok = all(torch.allclose(trained[k], rm.true_weights[k]) for k in trained)\n"
        "print(f'  Restored weights match trained: {restored_ok}')\n"
        "assert restored_ok\n"
        "rtr = resumed.get_trainer()\n"
        "_, rloss = rtr.train_step(ids, labels=ids)  # resume training (optimizer state restored)\n"
        "print(f'  Resumed training loss: {rloss:.4f}')\n"
        "print(f'  Resume verification: OK')\n"
        "resumed.close(); m.close()\n"
        "del resumed, m, rm, rtr\n"
        "import gc; gc.collect()\n"
        "if torch.cuda.is_available(): torch.cuda.empty_cache()\n"
        "print('All selective full-FT modes verified on ' + dev.upper())"
    )))

    # 16. DEMO: Selective Full Fine-Tuning on TinyLlama (STREAMING)
    notebook_cells.append(create_notebook_cell(
        "# DEMO: Selective Full-FT on TinyLlama 1.1B (STREAMING)\n"
        "# Trains q/k/v/o projections on the last 4 layers of a real 1.1B model\n"
        "# under the STREAMING (VRAM-virtualizing) strategy. Reports VRAM/RAM/step time.",
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(guarded(
        "import torch, gc, time, os, json\n"
        "from lema import LemaConfig, LemaModel, MemoryStrategy\n"
        "\n"
        "print('=== Selective Full-FT on TinyLlama 1.1B (STREAMING) ===')\n"
        "DEV_TL = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
        "outdir = os.path.join('/tmp', 'tinyllama_ft')\n"
        "config = LemaConfig(\n"
        "    model_name_or_path='TinyLlama/TinyLlama-1.1B-Chat-v1.0',\n"
        "    device=DEV_TL,\n"
        "    strategy=MemoryStrategy.STREAMING,\n"
        "    training_mode='selective_full',\n"
        "    trainable_modules=['q_proj','k_proj','v_proj','o_proj'],\n"
        "    trainable_layers=['last:4'],\n"
        "    learning_rate=1e-4,\n"
        "    gradient_accumulation_steps=1,\n"
        "    save_steps=6,\n"
        "    output_dir=outdir,\n"
        "    gradient_checkpointing=True,\n"
        ")\n"
        "model = LemaModel(config)\n"
        "mgr = model.full_ft_manager\n"
        "print(f'Selected layers: {sorted(mgr.selected.keys())}')\n"
        "print(f'Selected params: {mgr.total_selected_params():,} '\n"
        "      f'(~{mgr.total_selected_params()*4/1e9:.3f} GB fp32 for true weights + Adam)')\n"
        "\n"
        "trainer = model.get_trainer()\n"
        "input_ids = torch.randint(0, 32000, (1, 64)).to(DEV_TL)\n"
        "labels = input_ids.clone()\n"
        "\n"
        "if torch.cuda.is_available(): torch.cuda.reset_peak_memory_stats()\n"
        "t0 = time.perf_counter()\n"
        "_, loss = trainer.train_step(input_ids, labels=labels)\n"
        "if torch.cuda.is_available(): torch.cuda.synchronize()\n"
        "dt = (time.perf_counter() - t0) * 1000\n"
        "vram = torch.cuda.max_memory_allocated() / 1e9 if torch.cuda.is_available() else 0.0\n"
        "import psutil\n"
        "ram = psutil.Process().memory_info().rss / 1e9\n"
        "print(f'Step 1 — loss={loss:.4f}, {dt:.0f}ms/step, VRAM={vram:.2f}GB, RAM={ram:.2f}GB')\n"
        "\n"
        "for step in range(5):\n"
        "    t0 = time.perf_counter()\n"
        "    _, loss = trainer.train_step(input_ids, labels=labels)\n"
        "    if torch.cuda.is_available(): torch.cuda.synchronize()\n"
        "    dt = (time.perf_counter() - t0) * 1000\n"
        "    vram = torch.cuda.max_memory_allocated() / 1e9 if torch.cuda.is_available() else 0.0\n"
        "    ram = psutil.Process().memory_info().rss / 1e9\n"
        "    print(f'  Step {step+2}/6 — loss={loss:.4f}, {dt:.0f}ms/step, VRAM={vram:.2f}GB, RAM={ram:.2f}GB')\n"
        "\n"
        "ckpt = os.path.join(outdir, 'checkpoint-6')\n"
        "assert os.path.exists(os.path.join(ckpt, 'delta.safetensors')), 'delta checkpoint missing'\n"
        "with open(os.path.join(ckpt, 'delta.index.json')) as f:\n"
        "    nkeys = len(json.load(f)['weights'])\n"
        "print(f'Delta checkpoint: {nkeys} tensors (last-4-layers q/k/v/o); '\n"
        "      f'delta + index + optimizer_fullft.bin all present: '\n"
        "      f'{os.path.exists(os.path.join(ckpt, \"delta.index.json\")) and os.path.exists(os.path.join(ckpt, \"optimizer_fullft.bin\"))}')\n"
        "\n"
        "# Resume from checkpoint and continue training\n"
        "resumed = LemaModel.from_pretrained(ckpt)\n"
        "rm = resumed.full_ft_manager\n"
        "match = all(torch.allclose(mgr.true_weights[k], rm.true_weights[k]) for k in mgr.true_weights)\n"
        "print(f'Resume weights match: {match}')\n"
        "rtr = resumed.get_trainer()\n"
        "_, rloss = rtr.train_step(input_ids, labels=labels)\n"
        "print(f'Resumed step loss: {rloss:.4f}')\n"
        "resumed.close(); model.close()\n"
        "del resumed, model, rtr, trainer, mgr, rm\n"
        "gc.collect()\n"
        "if torch.cuda.is_available(): torch.cuda.empty_cache()\n"
        "print('=== TinyLlama selective full-FT verification: OK ===')"
    )))

    # 16b. DEMO: Quantized full-FT on TinyLlama (all four bits)
    notebook_cells.append(create_notebook_cell(
        "# DEMO: Quantized Full-FT on TinyLlama 1.1B (all four bits)\n"
        "# Trains the same selection twice — fp16 baseline vs int8-everything\n"
        "# (weights, optimizer states, gradient accumulators, KV cache) — and\n"
        "# reports loss, step time, peak RSS, and peak VRAM on a real model.",
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(guarded(
        "import torch, gc, time, os\n"
        "import psutil\n"
        "from lema import LemaConfig, LemaModel, MemoryStrategy\n"
        "\n"
        "DEV_Q = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
        "def make_quant_config(bits):\n"
        "    return LemaConfig(\n"
        "        model_name_or_path='TinyLlama/TinyLlama-1.1B-Chat-v1.0',\n"
        "        device=DEV_Q,\n"
        "        strategy=MemoryStrategy.STREAMING,\n"
        "        training_mode='selective_full',\n"
        "        trainable_modules=['q_proj','k_proj','v_proj','o_proj'],\n"
        "        trainable_layers=['last:2'],\n"
        "        learning_rate=1e-4,\n"
        "        gradient_accumulation_steps=1,\n"
        "        save_steps=0,\n"
        "        output_dir=os.path.join('/tmp', 'quant_ft'),\n"
        "        weights_bits=bits, opt_state_bits=bits, grad_acc_bits=bits, kv_bits=bits,\n"
        "    )\n"
        "\n"
        "def run(bits, label):\n"
        "    config = make_quant_config(bits)\n"
        "    model = LemaModel(config)\n"
        "    trainer = model.get_trainer()\n"
        "    input_ids = torch.randint(0, 32000, (1, 64)).to(DEV_Q)\n"
        "    labels = input_ids.clone()\n"
        "    if torch.cuda.is_available(): torch.cuda.reset_peak_memory_stats()\n"
        "    t0 = time.perf_counter()\n"
        "    _, loss = trainer.train_step(input_ids, labels=labels)\n"
        "    if torch.cuda.is_available(): torch.cuda.synchronize()\n"
        "    dt = (time.perf_counter() - t0) * 1000\n"
        "    t0 = time.perf_counter()\n"
        "    _, loss2 = trainer.train_step(input_ids, labels=labels)\n"
        "    if torch.cuda.is_available(): torch.cuda.synchronize()\n"
        "    dt2 = (time.perf_counter() - t0) * 1000\n"
        "    vram = torch.cuda.max_memory_allocated() / 1e9 if torch.cuda.is_available() else 0.0\n"
        "    ram = psutil.Process().memory_info().rss / 1e9\n"
        "    print(f'{label}: loss {loss:.4f} -> {loss2:.4f}, '\n"
        "          f'{dt:.0f}ms/{dt2:.0f}ms per step, peak VRAM {vram:.2f}GB, peak RSS {ram:.2f}GB')\n"
        "    model.close()\n"
        "    del model, trainer\n"
        "    gc.collect(); torch.cuda.empty_cache()\n"
        "    return loss, loss2, vram, ram\n"
        "\n"
        "print('=== Quantized full-FT on TinyLlama 1.1B: fp16 vs int8-all ===')\n"
        "base = run(None, 'fp16 baseline')\n"
        "q = run(8, 'int8-all')\n"
        "print(f'Loss gap vs baseline: {abs(q[0]-base[0]):.4f} (int8 weight error at load)')\n"
        "print(f'peak VRAM: baseline {base[2]:.2f}GB, int8-all {q[2]:.2f}GB '\n"
        "      f'(dequant slot adds VRAM; weights save RAM/PCIe, not VRAM)')\n"
        "print(f'peak RSS: baseline {base[3]:.2f}GB, int8-all {q[3]:.2f}GB')\n"
        "assert q[1] != q[0], 'quantized training did not advance'\n"
        "assert q[1] < q[0], 'quantized training loss did not decrease'\n"
        "assert abs(q[0] - base[0]) < 2.0, 'quantized loss diverged from fp16 baseline'\n"
        "assert abs(q[1] - q[0]) < abs(base[1] - base[0]) + 1.0, 'quantized training lost too much signal'\n"
        "print('=== Quantized full-FT verification: OK ===')"
    )))

    # 16c. DEMO: W8A8 native int8 compute vs fp16 baseline
    notebook_cells.append(create_notebook_cell(
        "# DEMO: W8A8 native int8 compute (weights_bits=8) vs fp16 baseline\n"
        "# Native int8xint8 GEMM kernels (AVX2 on CPU, DP4A on T4) consume raw\n"
        "# int8 streamed buffers directly - no fp32 dequant slot. Measures\n"
        "# disk->RAM->VRAM transfer bytes/time and full-FT step time, VRAM, RSS.",
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(
        "import torch, gc, time, os\n"
        "import psutil\n"
        "from lema import LemaConfig, LemaModel, MemoryStrategy\n"
        "from lema import _w8a8\n"
        "from lema._quant_backend import list_available_backends\n"
        "\n"
        "USE_CUDA_W8A8 = torch.cuda.is_available()\n"
        "DEV = 'cuda' if USE_CUDA_W8A8 else 'cpu'\n"
        "print(f'W8A8 native kernels available: {_w8a8.HAS_NATIVE} USE_CUDA={USE_CUDA_W8A8} DEV={DEV}')\n"
        "print(f'Available quant backends: {list_available_backends()}')\n"
        "\n"
        "def make_w8a8_config(bits, backend='auto'):\n"
        "    return LemaConfig(\n"
        "        model_name_or_path='TinyLlama/TinyLlama-1.1B-Chat-v1.0',\n"
        "        device=DEV,\n"
        "        strategy=MemoryStrategy.STREAMING,\n"
        "        training_mode='selective_full',\n"
        "        trainable_modules=['q_proj','k_proj','v_proj','o_proj'],\n"
        "        trainable_layers=['last:2'],\n"
        "        learning_rate=1e-4,\n"
        "        gradient_accumulation_steps=1,\n"
        "        save_steps=0,\n"
        "        output_dir=os.path.join('/tmp', 'w8a8_ft'),\n"
        "        weights_bits=bits,\n"
        "        quant_backend=backend,\n"
        "    )\n"
        "\n"
        "def layer_bytes(tr, layer_id):\n"
        "    return tr.layer_transfer_bytes(layer_id)\n"
        "\n"
        "def transfer_bench(model, label):\n"
        "    tr = model.store.transfer\n"
        "    layer_id = 1\n"
        "    nbytes = layer_bytes(tr, layer_id)\n"
        "    times = []\n"
        "    for _ in range(3):\n"
        "        tr.prefetch_to_ram(layer_id, slot=0)\n"
        "        if USE_CUDA_W8A8: torch.cuda.synchronize()\n"
        "        t0 = time.perf_counter()\n"
        "        tr.async_transfer_to_vram(layer_id, vram_slot=0, ram_slot=0)\n"
        "        tr.get_vram_flat_buffer(0)\n"
        "        if USE_CUDA_W8A8: torch.cuda.synchronize()\n"
        "        times.append(time.perf_counter() - t0)\n"
        "    print(f'{label}: RAM->VRAM {min(times)*1000:.2f}ms, buffer {nbytes/1e6:.1f}MB, '\n"
        "          f'{nbytes/1e6/max(min(times),1e-9)/1000:.1f}GB/s')\n"
        "    model.close()\n"
        "    del model\n"
        "    gc.collect()\n"
        "    if USE_CUDA_W8A8: torch.cuda.empty_cache()\n"
        "    return min(times), nbytes\n"
        "\n"
        "\n"
        "if RUN_SLOW_BENCHES:\n"
        "    tb_fp16 = transfer_bench(LemaModel(make_w8a8_config(None)), 'transfer fp16')\n"
        "    tb_q8 = transfer_bench(LemaModel(make_w8a8_config(8)), 'transfer int8 (on-fly)')\n"
        "    if _w8a8.HAS_NATIVE and USE_CUDA_W8A8:\n"
        "        assert tb_q8[1] < tb_fp16[1], 'int8 transfer must move fewer bytes than fp16'\n"
        "        print(f'transfer bytes: fp16 {tb_fp16[1]/1e6:.1f}MB -> int8 {tb_q8[1]/1e6:.1f}MB '\n"
        "              f'({tb_fp16[1]/tb_q8[1]:.1f}x reduction)')\n"
        "    else:\n"
        "        print(f'transfer bytes: fp16 {tb_fp16[1]/1e6:.1f}MB, int8 {tb_q8[1]/1e6:.1f}MB '\n"
        "              f'(no byte reduction without native kernels)')\n"
        "    # Pre-quantized transfer (quantize offline to avoid pack quant overhead)\n"
        "    try:\n"
        "        from safetensors.torch import save_file as _sf_save\n"
        "        from lema._gbi import GlobalBinaryIndex as _GBI\n"
        "        from lema._quant_backend import quantize_tensor_with_backend as _qtb\n"
        "        _preq_dir = '/tmp/tinyllama_prequant'\n"
        "        _tmp_m = LemaModel(make_w8a8_config(None))\n"
        "        _gbi = _tmp_m.store.transfer.gbi\n"
        "        _preq_tensors = {}\n"
        "        for _k in _gbi.get_keys():\n"
        "            _w = _gbi.load_tensors([_k])[_k]\n"
        "            if _w.ndim == 2:\n"
        "                _q, _s = _qtb(_w, 8, backend='custom')\n"
        "                _preq_tensors[_k] = _q\n"
        "                _preq_tensors[_k + '.scale'] = _s\n"
        "            else:\n"
        "                _preq_tensors[_k] = _w\n"
        "        _tmp_m.close()\n"
        "        del _tmp_m\n"
        "        gc.collect()\n"
        "        os.makedirs(_preq_dir, exist_ok=True)\n"
        "        _sf_save(_preq_tensors, os.path.join(_preq_dir, 'model.safetensors'))\n"
        "        _preq_cfg = make_w8a8_config(8, backend='custom')\n"
        "        _preq_cfg.gbi_path = os.path.join(_preq_dir, 'model.safetensors')\n"
        "        tb_preq = transfer_bench(LemaModel(_preq_cfg), 'transfer int8 (pre-quant)')\n"
        "        print(f'pre-quant transfer: int8 {tb_preq[1]/1e6:.1f}MB @ {tb_preq[0]*1000:.2f}ms vs on-fly {tb_q8[0]*1000:.2f}ms (should be faster, no quant at pack)')\n"
        "    except Exception as _e:\n"
        "        print(f'pre-quant transfer bench skipped: {_e}')\n"
        "\n"
        "def run_w8a8(bits, label, backend='auto', config=None):\n"
        "    config = config or make_w8a8_config(bits, backend=backend)\n"
        "    model = LemaModel(config)\n"
        "    trainer = model.get_trainer()\n"
        "    input_ids = torch.randint(0, 32000, (1, 64)).to(DEV)\n"
        "    labels = input_ids.clone()\n"
        "    if USE_CUDA_W8A8: torch.cuda.reset_peak_memory_stats()\n"
        "    t0 = time.perf_counter()\n"
        "    _, loss = trainer.train_step(input_ids, labels=labels)\n"
        "    if USE_CUDA_W8A8: torch.cuda.synchronize()\n"
        "    dt = (time.perf_counter() - t0) * 1000\n"
        "    t0 = time.perf_counter()\n"
        "    _, loss2 = trainer.train_step(input_ids, labels=labels)\n"
        "    if USE_CUDA_W8A8: torch.cuda.synchronize()\n"
        "    dt2 = (time.perf_counter() - t0) * 1000\n"
        "    vram = torch.cuda.max_memory_allocated() / 1e9 if USE_CUDA_W8A8 else 0.0\n"
        "    ram = psutil.Process().memory_info().rss / 1e9\n"
        "    print(f'{label}: loss {loss:.4f} -> {loss2:.4f}, '\n"
        "          f'{dt:.0f}ms/{dt2:.0f}ms per step, peak VRAM {vram:.2f}GB, peak RSS {ram:.2f}GB')\n"
        "    model.close()\n"
        "    del model, trainer\n"
        "    gc.collect()\n"
        "    if USE_CUDA_W8A8: torch.cuda.empty_cache()\n"
        "    return loss, loss2, dt, dt2, vram, ram\n"
        "\n"
        "wbase = None\n"
        "wq8_onfly = None\n"
        "_w4 = None\n"
        "print('=== W8A8 int8 compute vs fp16: TinyLlama full-FT last:2 ===')\n"
        "if not RUN_SLOW_BENCHES:\n"
        "    print('W8A8 on-fly sweep skipped (RUN_SLOW_BENCHES=False; results in v22 log)')\n"
        "if RUN_SLOW_BENCHES:\n"
        "    wbase = run_w8a8(None, 'fp16 baseline', backend='auto')\n"
        "    wq8_onfly = None\n"
        "    for backend in ['custom', 'torchao', 'quanto', 'bitsandbytes']:\n"
        "        avail = list_available_backends()\n"
        "        if backend not in avail:\n"
        "            print(f'skipping {backend}: not installed (pip install lema[{backend}])')\n"
        "            continue\n"
        "        if backend == 'bitsandbytes' and not USE_CUDA_W8A8:\n"
        "            print(f'skipping bitsandbytes: requires CUDA')\n"
        "            continue\n"
        "        wq8 = run_w8a8(8, f'int8-w8a8 ({backend})', backend=backend)\n"
        "        if backend == 'custom': wq8_onfly = wq8\n"
        "        assert wq8[1] != wq8[0], f'W8A8 {backend} training did not advance'\n"
        "        assert abs(wq8[0] - wbase[0]) < 2.0, f'W8A8 {backend} loss diverged'\n"
        "        speedup = wbase[3] / max(wq8[3], 1e-9)\n"
        "        vram_delta = wbase[4] - wq8[4]\n"
        "        rss_delta = wbase[5] - wq8[5]\n"
        "        print(f'  [{backend}] step2: fp16 {wbase[3]:.0f}ms -> {backend} {wq8[3]:.0f}ms ({speedup:.2f}x) VRAM {vram_delta*1000:+.0f}MB RSS {rss_delta*1000:+.0f}MB')\n"
        "        verdict = 'FASTER and CHEAPER' if (speedup > 1.0 and vram_delta > 0 and rss_delta > 0) else 'NOT yet faster-and-cheaper'\n"
        "        print(f'  [{backend}] verdict: {verdict}')\n"
        "    print('=== W8A8 backend sweep verification: OK ===')"
    ))

    # 15b. Per-backend quant parity + transfer bench
    notebook_cells.append(create_notebook_cell(
        "# Per-Backend Quant Bench\n"
        "# 1. Parity: quantize a real TinyLlama weight with every installed backend\n"
        "#    x bits {8,4}, measure pack time, wire bytes and roundtrip rel-error.\n"
        "#    (bnb/quanto bits=4 now explicitly warn + fall back to custom.)\n"
        "# 2. Transfer: full layer RAM->VRAM bench per backend/bits (int4 wire size too).\n"
        "# 3. int4 training step (custom format, dequant-at-use) - never GPU-benchmarked before.",
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(guarded(
        "import torch, gc, time, os\n"
        "from lema import LemaModel\n"
        "from lema._quant_backend import (quantize_tensor_with_backend, dequantize_with_backend,\n"
        "                                 list_available_backends)\n"
        "\n"
        "_avail = list_available_backends()\n"
        "_probe = LemaModel(make_w8a8_config(None))\n"
        "_WKEY = 'model.layers.1.self_attn.q_proj.weight'\n"
        "_wref = _probe.store.transfer.gbi.load_tensors([_WKEY])[_WKEY].detach().float()\n"
        "_probe.close()\n"
        "del _probe\n"
        "gc.collect()\n"
        "if USE_CUDA_W8A8: torch.cuda.empty_cache()\n"
        "\n"
        "print(f'=== Per-backend quant parity (weight {tuple(_wref.shape)}, {_wref.numel()/1e6:.2f}M elems) ===')\n"
        "_parity = {}\n"
        "for _b in ['custom', 'torchao', 'quanto', 'bitsandbytes']:\n"
        "    if _b not in _avail:\n"
        "        print(f'  {_b}: not installed - skipped')\n"
        "        continue\n"
        "    for _bits in (8, 4):\n"
        "        _t0 = time.perf_counter()\n"
        "        _q, _s = quantize_tensor_with_backend(_wref, _bits, backend=_b)\n"
        "        _tq = (time.perf_counter() - _t0) * 1000\n"
        "        _dq = dequantize_with_backend(_q, _s, bits=_bits)\n"
        "        _rel = ((_dq - _wref).abs().max() / _wref.abs().max()).item()\n"
        "        _wire = _q.numel() * _q.element_size() + _s.numel() * _s.element_size()\n"
        "        _parity[(_b, _bits)] = _rel\n"
        "        print(f'  {_b} bits={_bits}: pack {_tq:.2f}ms, wire {_wire/1e6:.2f}MB, rel-err {_rel:.4f}')\n"
        "        assert _rel < 0.12, f'{_b} bits={_bits} rel error {_rel:.4f} too large'\n"
        "print('=== Quant parity verification: OK ===')\n"
        "\n"
        "print('=== Per-backend layer transfer (layer 1, on-fly pack) ===')\n"
        "_tb = {}\n"
        "for _b in ['custom', 'torchao', 'quanto', 'bitsandbytes']:\n"
        "    if _b not in _avail:\n"
        "        continue\n"
        "    for _bits in (8, 4):\n"
        "        _tb[(_b, _bits)] = transfer_bench(\n"
        "            LemaModel(make_w8a8_config(_bits, backend=_b)), f'transfer {_b} bits={_bits}')\n"
        "if ('custom', 8) in _tb and ('custom', 4) in _tb:\n"
        "    print(f'int4 vs int8 wire: {_tb[(\"custom\", 4)][1]/1e6:.1f}MB'\n"
        "          f' vs {_tb[(\"custom\", 8)][1]/1e6:.1f}MB')\n"
        "\n"
        "if USE_CUDA_W8A8:\n"
        "    print('=== int4 training step (custom fmt, dequant-at-use) ===')\n"
        "    _w4 = run_w8a8(4, 'int4-w4a16 (custom)', backend='custom')\n"
        "    assert _w4[1] != _w4[0], 'int4 training did not advance'\n"
        "print('=== Per-backend bench verification: OK ===')"
    )))

    # 15c. W8A8 step-time breakdown (profiling evidence for the step bottleneck)
    notebook_cells.append(create_notebook_cell(
        "# W8A8 Step-Time Breakdown\n"
        "# Monkeypatch-based phase timers around train_step internals:\n"
        "#   pack_wait  = wait_prefetch (pipeline stall on RAM quantize/pack)\n"
        "#   xfer       = async_transfer_to_vram enqueue cost\n"
        "#   construct  = construct_layer_module (layer rebuild, int8 vs fp16)\n"
        "#   forward    = forward_layer (no-grad fwd + grad re-forward)\n"
        "#   backward   = tensor .backward() calls\n"
        "#   accum/clip/optim = full-FT grad accumulation, clipping, optimizer step\n"
        "# Plus torch.profiler top CUDA kernels for one step: fp16 vs W8A8 custom.",
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(
        "import torch, gc, time, os\n"
        "from lema import LemaModel\n"
        "\n"
        "def profile_train_step(bits, backend, label, n_steps=3, config=None):\n"
        "    config = config or make_w8a8_config(bits, backend=backend)\n"
        "    model = LemaModel(config)\n"
        "    trainer = model.get_trainer()\n"
        "    tr = trainer.memory\n"
        "    adapter = trainer.adapter\n"
        "    ffm = trainer.full_ft_manager\n"
        "    T = {'pack_wait': 0.0, 'xfer': 0.0, 'construct': 0.0, 'forward': 0.0,\n"
        "         'backward': 0.0, 'accum': 0.0, 'clip': 0.0, 'optim': 0.0}\n"
        "    installed = []\n"
        "\n"
        "    def _wrap(obj, name, key):\n"
        "        orig = getattr(obj, name)\n"
        "        def _timed(*a, **k):\n"
        "            t0 = time.perf_counter()\n"
        "            try:\n"
        "                return orig(*a, **k)\n"
        "            finally:\n"
        "                T[key] += time.perf_counter() - t0\n"
        "        setattr(obj, name, _timed)\n"
        "        installed.append((obj, name, orig))\n"
        "\n"
        "    _wrap(tr, 'wait_prefetch', 'pack_wait')\n"
        "    _wrap(tr, 'async_transfer_to_vram', 'xfer')\n"
        "    _wrap(adapter, 'construct_layer_module', 'construct')\n"
        "    _wrap(adapter, 'forward_layer', 'forward')\n"
        "    if ffm is not None:\n"
        "        _wrap(ffm, 'accumulate_grads', 'accum')\n"
        "        _wrap(ffm, 'clip_grad_norm_', 'clip')\n"
        "        _wrap(ffm, 'step_layer', 'optim')\n"
        "    _bw = torch.Tensor.backward\n"
        "    def _bw_timed(self, *a, **k):\n"
        "        t0 = time.perf_counter()\n"
        "        try:\n"
        "            return _bw(self, *a, **k)\n"
        "        finally:\n"
        "            T['backward'] += time.perf_counter() - t0\n"
        "    torch.Tensor.backward = _bw_timed\n"
        "\n"
        "    input_ids = torch.randint(0, 32000, (1, 64)).to(DEV)\n"
        "    labels = input_ids.clone()\n"
        "    walls = []\n"
        "    try:\n"
        "        for _ in range(n_steps):\n"
        "            t0 = time.perf_counter()\n"
        "            trainer.train_step(input_ids, labels=labels)\n"
        "            if USE_CUDA_W8A8: torch.cuda.synchronize()\n"
        "            walls.append(time.perf_counter() - t0)\n"
        "    finally:\n"
        "        torch.Tensor.backward = _bw\n"
        "        for obj, name, orig in installed:\n"
        "            setattr(obj, name, orig)\n"
        "        model.close()\n"
        "    del model, trainer\n"
        "    gc.collect()\n"
        "    if USE_CUDA_W8A8: torch.cuda.empty_cache()\n"
        "\n"
        "    n = max(len(walls), 1)\n"
        "    wall = sum(walls) / n * 1000\n"
        "    print(f'--- {label}: wall {wall:.0f}ms/step (avg of {n}) ---')\n"
        "    _acc = 0.0\n"
        "    for _k in ['pack_wait', 'xfer', 'construct', 'forward', 'backward', 'accum', 'clip', 'optim']:\n"
        "        _ms = T[_k] / n * 1000\n"
        "        _acc += _ms\n"
        "        if _ms > 0.05:\n"
        "            print(f'  {_k:<10}: {_ms:8.1f}ms ({_ms / wall * 100:4.1f}%)')\n"
        "    print(f'  {\"sum\":<10}: {_acc:8.1f}ms (rest = launch/sync overhead)')\n"
        "    return wall\n"
        "\n"
        "if not RUN_SLOW_BENCHES:\n"
        "    print('Step-time breakdown skipped (RUN_SLOW_BENCHES=False; results in v22 log)')\n"
        "if RUN_SLOW_BENCHES:\n"
        "    print('=== Step-time breakdown: fp16 vs W8A8 backends ===')\n"
        "    profile_train_step(None, 'auto', 'fp16')\n"
        "    for _b in ['custom', 'torchao', 'quanto', 'bitsandbytes']:\n"
        "        if _b not in _avail:\n"
        "            print(f'  {_b}: not installed - skipped')\n"
        "            continue\n"
        "        profile_train_step(8, _b, f'int8-w8a8 ({_b})')\n"
        "\n"
        "def top_kernels(bits, backend, label):\n"
        "    if not USE_CUDA_W8A8:\n"
        "        print(f'  {label}: skipped (no CUDA)')\n"
        "        return\n"
        "    from torch.profiler import profile, ProfilerActivity\n"
        "    config = make_w8a8_config(bits, backend=backend)\n"
        "    model = LemaModel(config)\n"
        "    trainer = model.get_trainer()\n"
        "    input_ids = torch.randint(0, 32000, (1, 64)).to(DEV)\n"
        "    labels = input_ids.clone()\n"
        "    trainer.train_step(input_ids, labels=labels)  # warmup\n"
        "    torch.cuda.synchronize()\n"
        "    with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA]) as prof:\n"
        "        trainer.train_step(input_ids, labels=labels)\n"
        "        torch.cuda.synchronize()\n"
        "    print(f'--- {label}: top CUDA kernels ---')\n"
        "    print(prof.key_averages().table(sort_by='cuda_time_total', row_limit=8,\n"
        "                                    max_name_column_width=60))\n"
        "    model.close()\n"
        "    del model, trainer\n"
        "    gc.collect()\n"
        "    torch.cuda.empty_cache()\n"
        "\n"
        "print('=== torch.profiler: fp16 vs W8A8 custom (1 step) ===')\n"
        "if RUN_SLOW_BENCHES:\n"
        "    top_kernels(None, 'auto', 'fp16')\n"
        "    top_kernels(8, 'custom', 'W8A8 custom')\n"
        "    print('=== Step-time breakdown verification: OK ===')"
    ))

    # 15d. Pre-quant W8A8 training sweep (re-test faster-and-cheaper without CPU quantize)
    notebook_cells.append(create_notebook_cell(
        "# Pre-Quant W8A8 Training Sweep (per quantization level)\n"
        "# v22 evidence: on-fly W8A8 is 15-16s/step, ~83-85% of it pack_wait =\n"
        "# CPU on-the-fly per-row quantize of ~131MB/layer on 2-vCPU Kaggle.\n"
        "# For EACH level (int4 AND int8) we pre-quantize a DEDICATED checkpoint\n"
        "# here (raw packed-int + scales on disk; NOT the transfer bench's\n"
        "# checkpoint), then benchmark training on it: pack becomes a raw byte\n"
        "# copy with ZERO CPU quantize -> pack_wait should collapse to fp16\n"
        "# levels and 'faster-and-cheaper' becomes testable per level.",
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(
        "import torch, gc, time, os, json, math\n"
        "from safetensors.torch import save_file as _pq_save\n"
        "from lema import LemaModel\n"
        "from lema._quant_backend import quantize_tensor_with_backend\n"
        "\n"
        "def build_preq_ckpt(bits):\n"
        "    # Dedicated checkpoint per quantization level (fresh, not shared with the transfer bench).\n"
        "    d = f'/tmp/tinyllama_preq_w{bits}'\n"
        "    p = os.path.join(d, 'model.safetensors')\n"
        "    if os.path.exists(p):\n"
        "        print(f'reusing {p} (built earlier in this session)')\n"
        "        return p\n"
        "    print(f'building pre-quant int{bits} checkpoint (custom fmt, all 2D tensors)...')\n"
        "    _m = LemaModel(make_w8a8_config(None))\n"
        "    _gbi = _m.store.transfer.gbi\n"
        "    _t = {}\n"
        "    _logical = {}\n"
        "    _t0 = time.perf_counter()\n"
        "    for _k in _gbi.get_keys():\n"
        "        _w = _gbi.load_tensors([_k])[_k]\n"
        "        if _w.ndim == 2:\n"
        "            _q, _s = quantize_tensor_with_backend(_w, bits, backend='custom')\n"
        "            if bits == 4:\n"
        "                # packed uint8 halves storage numel; record true logical shape\n"
        "                _logical[_k] = list(_w.shape)\n"
        "            _t[_k] = _q\n"
        "            _t[_k + '.scale'] = _s\n"
        "        else:\n"
        "            _t[_k] = _w\n"
        "    _m.close()\n"
        "    del _m\n"
        "    gc.collect()\n"
        "    os.makedirs(d, exist_ok=True)\n"
        "    _meta = {'lema_logical_shapes': json.dumps(_logical)} if _logical else None\n"
        "    _pq_save(_t, p, metadata=_meta)\n"
        "    print(f'  built int{bits} in {time.perf_counter()-_t0:.0f}s')\n"
        "    return p\n"
        "\n"
        "print('=== Pre-quant training sweep: pre-quantize per level (4-bit, 8-bit), then bench ===')\n"
        "\n"
        "def _diag_preq(bits, cfg, n=3):\n"
        "    # Instrumented 3-step run to localize a flat-loss (no-advance) result.\n"
        "    # Per step prints: loss, |dw|max vs step-0 weights, accumulator max/norm/nonzero-count\n"
        "    # (sparsity of what actually accumulated), pre-clip grad norm (is clipping engaged?),\n"
        "    # grads_seen (matched params holding a grad at accumulate time) vs n_map (mapping size),\n"
        "    # and an apply_to_module effectiveness check (module param vs true_weights after apply).\n"
        "    print(f'--- diagnostic: instrumented {n}-step run ({bits}-bit pre-quant) ---')\n"
        "    model = LemaModel(cfg)\n"
        "    tr = model.get_trainer()\n"
        "    ffm = tr.full_ft_manager\n"
        "    ids = torch.randint(0, 32000, (1, 64)).to(DEV)\n"
        "    ev = {'acc_max': [], 'acc_nz': [], 'acc_norm': [], 'gnorm': [], 'ng': [], 'nmap': [], 'apply_d': []}\n"
        "    _orig_step, _orig_acc = ffm.step_layer, ffm.accumulate_grads\n"
        "    _orig_clip, _orig_apply = ffm.clip_grad_norm_, ffm.apply_to_module\n"
        "    def _acc(layer_id, module):\n"
        "        n2k = ffm.module_name_to_key.get(layer_id, {})\n"
        "        ev['nmap'].append(len(n2k))\n"
        "        ev['ng'].append(sum(1 for name, p in module.named_parameters()\n"
        "                            if name in n2k and p.grad is not None))\n"
        "        _orig_acc(layer_id, module)\n"
        "    def _clip(layer_id, max_norm=1.0):\n"
        "        keys = ffm.selected_layer_keys.get(layer_id, [])\n"
        "        tot = 0.0\n"
        "        for k in keys:\n"
        "            a = ffm.get_accumulator(k)\n"
        "            d = ffm._deq_acc(a, k) if isinstance(a, tuple) else a\n"
        "            tot += d.float().pow(2).sum().item()\n"
        "        ev['gnorm'].append(math.sqrt(tot))\n"
        "        return _orig_clip(layer_id, max_norm)\n"
        "    def _step(layer_id):\n"
        "        mx, nz, sq = 0.0, 0, 0.0\n"
        "        for k in ffm.selected_layer_keys.get(layer_id, []):\n"
        "            a = ffm.get_accumulator(k)\n"
        "            d = ffm._deq_acc(a, k) if isinstance(a, tuple) else a\n"
        "            mx = max(mx, d.abs().max().item())\n"
        "            nz += int((d != 0).sum().item())\n"
        "            sq += d.float().pow(2).sum().item()\n"
        "        ev['acc_max'].append(mx)\n"
        "        ev['acc_nz'].append(nz)\n"
        "        ev['acc_norm'].append(math.sqrt(sq))\n"
        "        _orig_step(layer_id)\n"
        "    def _apply(layer_id, module):\n"
        "        _orig_apply(layer_id, module)\n"
        "        if layer_id in ffm.selected_layer_keys and ev['apply_d'] == []:\n"
        "            n2k = ffm.module_name_to_key.get(layer_id, {})\n"
        "            worst = 0.0\n"
        "            for name, p in module.named_parameters():\n"
        "                if name in n2k:\n"
        "                    worst = max(worst, (p.data.float() - ffm.true_weights[n2k[name]].float().to(p.device)).abs().max().item())\n"
        "            ev['apply_d'].append(worst)\n"
        "    ffm.accumulate_grads, ffm.step_layer = _acc, _step\n"
        "    ffm.clip_grad_norm_, ffm.apply_to_module = _clip, _apply\n"
        "    w0 = {k: w.detach().clone() for k, w in ffm.true_weights.items()}\n"
        "    try:\n"
        "        for i in range(n):\n"
        "            l = tr.train_step(ids, labels=ids)\n"
        "            l = float(l[1]) if isinstance(l, tuple) else float(l)\n"
        "            dw = max((ffm.true_weights[k].float() - w0[k].float()).abs().max().item() for k in w0)\n"
        "            am = ev['acc_max'][-1] if ev['acc_max'] else float('nan')\n"
        "            an = ev['acc_nz'][-1] if ev['acc_nz'] else -1\n"
        "            anorm = ev['acc_norm'][-1] if ev['acc_norm'] else float('nan')\n"
        "            gn = ev['gnorm'][-1] if ev['gnorm'] else float('nan')\n"
        "            ng = ev['ng'][-1] if ev['ng'] else 0\n"
        "            nm = ev['nmap'][-1] if ev['nmap'] else 0\n"
        "            ad = ev['apply_d'][0] if ev['apply_d'] else float('nan')\n"
        "            print(f'  step {i}: loss={l:.6f} |dw|max={dw:.3e} acc_max={am:.3e} '\n"
        "                  f'acc_nz={an} acc_norm={anorm:.3e} gnorm(pre-clip)={gn:.3e} '\n"
        "                  f'grads_seen={ng}/{nm} apply_diff={ad:.3e}')\n"
        "    finally:\n"
        "        ffm.accumulate_grads, ffm.step_layer = _orig_acc, _orig_step\n"
        "        ffm.clip_grad_norm_, ffm.apply_to_module = _orig_clip, _orig_apply\n"
        "        model.close()\n"
        "    del model\n"
        "    gc.collect()\n"
        "\n"
        "if USE_CUDA_W8A8:\n"
        "    for _bits in (8, 4):\n"
        "        _lbl = 'int8-w8a8 (pre-quant)' if _bits == 8 else 'int4-w4a16 (pre-quant)'\n"
        "        _onfly = globals().get('wq8_onfly') if _bits == 8 else globals().get('_w4')\n"
        "        _cfg = make_w8a8_config(_bits, backend='custom')\n"
        "        _cfg.gbi_path = build_preq_ckpt(_bits)\n"
        "        _wp = run_w8a8(_bits, _lbl, backend='custom', config=_cfg)\n"
        "        if _wp[1] == _wp[0]:\n"
        "            print(f'WARNING: {_lbl} training did not advance ({_wp[0]} -> {_wp[1]}) - running diagnostics')\n"
        "            _diag_preq(_bits, _cfg)\n"
        "        _wb = globals().get('wbase')\n"
        "        if _wb is None:\n"
        "            print('fp16 baseline not in globals (on-fly sweep skipped) - running quick baseline')\n"
        "            _wb = run_w8a8(None, 'fp16 baseline', backend='auto')\n"
        "            wbase = _wb\n"
        "        if _wb is not None:\n"
        "            if abs(_wp[0] - _wb[0]) >= 2.0:\n"
        "                print(f'WARNING: {_lbl} loss diverged vs fp16 baseline ({_wp[0]} vs {_wb[0]})')\n"
        "            _sp = _wb[3] / max(_wp[3], 1e-9)\n"
        "            _vd = _wb[4] - _wp[4]\n"
        "            _rd = _wb[5] - _wp[5]\n"
        "            print(f'  [{_lbl}] step2: fp16 {_wb[3]:.0f}ms -> pre-quant {_wp[3]:.0f}ms ({_sp:.2f}x) '\n"
        "                  f'VRAM {_vd*1000:+.0f}MB RSS {_rd*1000:+.0f}MB')\n"
        "            _verd = 'FASTER and CHEAPER' if (_sp > 1.0 and _vd > 0 and _rd > 0) else 'NOT yet faster-and-cheaper'\n"
        "            print(f'  [{_lbl}] verdict: {_verd}')\n"
        "            if _onfly is not None:\n"
        "                _xf = _onfly[3] / max(_wp[3], 1e-9)\n"
        "                print(f'  [{_lbl}] vs on-fly: {_onfly[3]:.0f}ms -> {_wp[3]:.0f}ms ({_xf:.2f}x), '\n"
        "                      f'loss {_onfly[1]:.4f} (on-fly) vs {_wp[1]:.4f} (pre-quant)')\n"
        "        print(f'--- {_lbl} step-time breakdown (expect pack_wait collapse) ---')\n"
        "        profile_train_step(_bits, 'custom', _lbl, config=_cfg)\n"
        "else:\n"
        "    print('pre-quant W8A8 sweep skipped (no CUDA)')\n"
        "print('=== Pre-quant W8A8 sweep verification: OK ===')"
    ))

    # 16. Adapter Verification (pytest)
    notebook_cells.append(create_notebook_cell(
        "# Adapter Verification\n"
        "# Runs unit tests for all model adapters.",
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(
        "!pytest tests/ -v --tb=short 2>&1 | head -60"
    ))

    # 16. LFM2.5 Verification
    notebook_cells.append(create_notebook_cell(
        "# LFM2.5 8B A1B Verification\n"
        "# Loads the model, runs forward/backward steps with dummy data.",
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(guarded(
        "import torch, gc, time\n"
        "from lema import LemaConfig, LemaModel, MemoryStrategy\n"
        "\n"
        "DEV_LFM2 = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
        "print(f'=== LFM2.5 8B A1B: Load & Verify (DEV={DEV_LFM2}) ===')\n"
        "config = LemaConfig(\n"
        "    model_name_or_path='LiquidAI/LFM2.5-8B-A1B',\n"
        "    device=DEV_LFM2,\n"
        "    strategy=MemoryStrategy.STREAMING,\n"
        "    lora_rank=8,\n"
        "    lora_target_modules=['q_proj','k_proj','v_proj','out_proj','w1','w2','w3'],\n"
        "    gradient_checkpointing=True,\n"
        ")\n"
        "model = LemaModel(config)\n"
        "model.initialize_lora()\n"
        "optimizer = torch.optim.AdamW(model.get_trainable_parameters(), lr=1e-4)\n"
        "trainer = model.get_trainer(optimizer)\n"
        "\n"
        "input_ids = torch.randint(0, 1000, (1, 128)).to(DEV_LFM2)\n"
        "logits, loss = trainer.train_step(input_ids, labels=input_ids)\n"
        "if torch.cuda.is_available(): torch.cuda.synchronize()\n"
        "print(f'Step 1 — loss={loss:.4f}, logits={logits.shape}')\n"
        "\n"
        "for step in range(4):\n"
        "    t0 = time.perf_counter()\n"
        "    _, loss = trainer.train_step(input_ids, labels=input_ids)\n"
        "    if torch.cuda.is_available(): torch.cuda.synchronize()\n"
        "    dt = (time.perf_counter() - t0) * 1000\n"
        "    print(f'  Step {step+2}/5 — loss={loss:.4f}, time={dt:.0f}ms')\n"
        "\n"
        "print('=== LFM2.5 8B A1B: Verification complete ===')\n"
        "model.close()\n"
        "del model, trainer, optimizer\n"
        "gc.collect()\n"
        "if torch.cuda.is_available(): torch.cuda.empty_cache()"
    )))

    # 17. DEMO: TensorStore — chunked long-context training + KV-cached generation
    notebook_cells.append(create_notebook_cell(
        "# DEMO: TensorStore Umbrella — Chunked Long-Context + KV-Cached Generation\n"
        "# Verifies the unified TensorStore: chunked attention on a sequence longer than\n"
        "# one KV chunk is exact vs full attention, and KV-cached generation matches the\n"
        "# old O(n^2) re-forward loop.",
        cell_type="markdown"
    ))
    notebook_cells.append(create_notebook_cell(
        "import torch, time, gc\n"
        "from lema import LemaConfig, LemaModel, MemoryStrategy\n"
        "from lema._tensorstore import KVChunkStore, chunked_attention\n"
        "from transformers import GPT2Config, GPT2LMHeadModel\n"
        "from safetensors.torch import save_file\n"
        "import tempfile, os\n"
        "\n"
        "dev = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
        "print('=== TensorStore: exact chunked attention ===')\n"
        "torch.manual_seed(0)\n"
        "q = torch.randn(2, 4, 16, 8, device=dev)\n"
        "k = torch.randn(2, 4, 32, 8, device=dev)\n"
        "v = torch.randn(2, 4, 32, 8, device=dev)\n"
        "chunks = [(k[:, :, i:i+8], v[:, :, i:i+8]) for i in range(0, 32, 8)]\n"
        "out = chunked_attention(q, chunks)\n"
        "scores = (q.float() @ k.float().transpose(-2, -1)) / (8 ** 0.5)\n"
        "m = scores.max(-1, keepdim=True).values\n"
        "p = (scores - m).exp()\n"
        "ref = (p @ v.float()) / p.sum(-1, keepdim=True)\n"
        "print(f'  chunked vs full max diff: {(out.float()-ref.float()).abs().max().item():.2e}')\n"
        "assert torch.allclose(out.float(), ref.float(), atol=1e-5, rtol=1e-5), 'chunked attention mismatch!'\n"
        "print('  OK — chunked attention exact')\n"
        "\n"
        "# Long-context chunked forward on GPT-2 (seq=64 > chunk=16)\n"
        "print('=== TensorStore: long-context chunked forward (GPT-2) ===')\n"
        "hf_cfg = GPT2Config(vocab_size=100, n_positions=128, n_embd=32, n_layer=2, n_head=2)\n"
        "hf_model = GPT2LMHeadModel(hf_cfg)\n"
        "sd = {kk: vv.clone() for kk, vv in hf_model.state_dict().items()}\n"
        "del hf_model\n"
        "tmp = tempfile.mkdtemp()\n"
        "model_path = os.path.join(tmp, 'model.safetensors')\n"
        "save_file(sd, model_path)\n"
        "hf_cfg.save_pretrained(tmp)\n"
        "config = LemaConfig(model_name_or_path=tmp, model_type='gpt2', gbi_path=model_path,\n"
        "                     device=dev, strategy=MemoryStrategy.STREAMING, max_vram_gb=8.0,\n"
        "                     kv_chunk_size=16)\n"
        "model = LemaModel(config)\n"
        "ad = model.adapter\n"
        "hidden = torch.randn(1, 64, ad.hidden_size, device=dev)\n"
        "tr = model.store.transfer\n"
        "tr.prefetch_to_ram(1, slot=0)\n"
        "tr.async_transfer_to_vram(1, vram_slot=0, ram_slot=0)\n"
        "flat = tr.get_vram_flat_buffer(0)\n"
        "block = ad.construct_layer_module(1, flat, None)\n"
        "block.eval()\n"
        "full_out = ad.forward_layer(block, hidden)\n"
        "kv_store = KVChunkStore(kv_chunk_size=16, device=dev)\n"
        "chunked_out = ad.chunked_forward_layer(block, hidden, kv_store, 1, kv_chunk_size=16)\n"
        "diff = (full_out.float() - chunked_out.float()).abs().max().item()\n"
        "print(f'  chunked forward vs full max diff: {diff:.2e}')\n"
        "assert diff < 1e-4, 'chunked forward mismatch!'\n"
        "print('  OK — chunked long-context forward exact')\n"
        "\n"
        "# KV-cached generation matches old re-forward\n"
        "print('=== TensorStore: KV-cached generation ===')\n"
        "class Tok:\n"
        "    eos_token_id = 2\n"
        "    def __call__(self, prompt, return_tensors='pt'):\n"
        "        ids = torch.tensor([[1, 3, 5, 7]])\n"
        "        class W(dict):\n"
        "            def to(self, dev):\n"
        "                self['input_ids'] = self['input_ids'].to(dev); return self\n"
        "        return W(input_ids=ids)\n"
        "    def decode(self, ids, skip_special_tokens=True):\n"
        "        return ','.join(str(int(x)) for x in ids.tolist())\n"
        "tok = Tok()\n"
        "torch.manual_seed(1)\n"
        "t0 = time.perf_counter()\n"
        "out_old = model.generate('x', tok, max_new_tokens=12, do_sample=False)\n"
        "t_old = time.perf_counter() - t0\n"
        "torch.manual_seed(1)\n"
        "t0 = time.perf_counter()\n"
        "out_kv = model.generate_kv('x', tok, max_new_tokens=12, do_sample=False, kv_chunk_size=16)\n"
        "t_kv = time.perf_counter() - t0\n"
        "print(f'  old re-forward: {out_old} ({t_old*1000:.1f} ms)')\n"
        "print(f'  KV-cached:      {out_kv} ({t_kv*1000:.1f} ms)')\n"
        "assert out_old == out_kv, f'generation mismatch: {out_old} vs {out_kv}'\n"
        "print(f'  OK — KV-cached generation matches old output')\n"
        "\n"
        "# Budget engine report\n"
        "print('=== TensorStore: budget tuning ===')\n"
        "report = model.tune_budgets()\n"
        "print('  per-kind VRAM (GB):', {k.value: round(v, 2) for k, v in report.per_kind_gb.items()})\n"
        "print('=== TensorStore umbrella verification: OK ===')\n"
        "model.close()\n"
        "del model; gc.collect(); torch.cuda.empty_cache()"
    ))

    # Construct Notebook JSON
    notebook = {
        "cells": notebook_cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.12"}
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }

    output_path = "examples/kaggle/benchmark.ipynb"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)

    print(f"Generated {output_path} — {len(notebook_cells)} cells")


if __name__ == "__main__":
    main()
